@table\attachment_headers.sql
@table\attachment_original.sql
@table\labels.sql
@table\messages.sql
@table\message_attachments.sql
@table\message_headers.sql
@table\message_original.sql
@table\process_monitor.sql
@table\process_monitor_detail.sql
@java_source\getpropertie.sql
@function\blob_to_clob.sql
@function\get_propertie.sql
@package_spec\google_api.sql
@package_spec\pls_logger.sql
@package_body\google_api.sql
@package_body\pls_logger.sql
@ref_constraint\message_headers_fk.sql
@ref_constraint\monitor_id_fk.sql
