CREATE TABLE "LABELS" (
	"ID" VARCHAR2(50 CHAR),
	"NAME" VARCHAR2(128 CHAR),
	"MESSAGELISTVISIBILITY" VARCHAR2(30 CHAR),
	"LABELLISTVISIBILITY" VARCHAR2(30 CHAR),
	"TYPE" VARCHAR2(30 CHAR),
	"MESSAGESTOTAL" NUMBER,
	"MESSAGESUNREAD" NUMBER,
	"THREADSTOTAL" NUMBER,
	"THREADSUNREAD" NUMBER,
	"TEXTCOLOR" VARCHAR2(30 CHAR),
	"BACKGROUNDCOLOR" VARCHAR2(30 CHAR),
	"CHANGE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	CONSTRAINT "LABELS_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
);