CREATE TABLE "MESSAGE_ATTACHMENTS" (
  "ID" VARCHAR2(20) NOT NULL ENABLE,
  "PART_ID" VARCHAR2(10),
  "ATTACHMENT_ID" VARCHAR2(512 CHAR),
  "MIMETYPE" VARCHAR2(128 CHAR),
  "FILENAME" VARCHAR2(128 CHAR),
  "BODY_SIZE" NUMBER,
  "ATTACHMENT" BLOB,
  "ATTACHMENT_CLOB" CLOB,
  CONSTRAINT "MESSAGE_ATTACHMENTS_UK" UNIQUE ("ID", "PART_ID", "ATTACHMENT_ID") USING INDEX ENABLE
);